version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DB_HOST=postgres
      - DB_USER=your_database_user
      - DB_PASSWORD=your_database_password
      - DB_NAME=your_database_name
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
